(feat) Implement initial functionality in `HumanRenderer` for diagnostic messages rendering.
Note that `HumanRenderer` is still under development and is not fully complete.

- Introduce `HumanRenderer` class to render human-friendly diagnostic messages.
- Currently implement rendering for title messages (e.g., "error[E0001]: error message.") and file-name, line-number, column-number triplets.